server:
  port: 8090
spring:
  application:
    name: msvc-product
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.format_sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: 150919